<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Dashboard | Lilsley Logistics</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&family=Open+Sans:wght@400;600&display=swap" rel="stylesheet">
   @include('admin.styles')
</head>
<body>
    <!-- Login Page -->
    <div id="loginPage" class="login-container">
        <div class="login-box">
            <div class="login-logo">Lilsley <span>Logistics</span></div>
            <div class="login-header">
                <h1>Admin Dashboard</h1>
                <p>Sign in to manage your logistics operations</p>
            </div>
            
            <form id="loginForm">
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" id="username" class="form-control" placeholder="Enter username" required>
                </div>
                
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" id="password" class="form-control" placeholder="Enter password" required>
                </div>
                
                <div class="form-group">
                    <button type="submit" class="btn btn-login">Sign In</button>
                </div>
            </form>
            
            <div class="login-footer">
                <p>Default credentials: admin / password123</p>
                <p>&copy; 2023 Lilsley Logistics. All rights reserved.</p>
            </div>
        </div>
    </div>
    
    <!-- Admin Dashboard -->
    <div id="dashboard" class="dashboard-container hidden">
        <!-- Sidebar -->
        @include('admin.sidebar')
        
        <!-- Main Content -->
        <main class="main-content">
            <!-- Top Header -->
            @include('admin.header')
            <!-- Dashboard Page -->
            
            @include('admin.overview')
            <!-- Services Management Page -->
            @include('admin.services-management')
            
            <!-- Products Management Page -->
           @include('admin.products-management')
            
            <!-- Shipments Management Page -->
            @include('admin.shipments-management')
            
            <!-- Inventory Management Page -->
           @include('admin.inventory-management')
            
            <!-- Orders Management Page -->
            @include('admin.orders-management')
            
            <!-- Customers Management Page -->
           @include('admin.customers-management')
            
            <!-- Reports Page -->
            <section id="reportsPage" class="admin-page hidden">
                <div class="dashboard-cards mb-4">
                    <div class="card">
                        <div class="card-content text-center">
                            <i class="fas fa-file-pdf" style="font-size: 2.5rem; color: var(--danger); margin-bottom: 15px;"></i>
                            <h3>Monthly Report</h3>
                            <p>Generate and download monthly performance report</p>
                            <button class="btn mt-4">Generate PDF</button>
                        </div>
                    </div>
                    
                    <div class="card">
                        <div class="card-content text-center">
                            <i class="fas fa-file-excel" style="font-size: 2.5rem; color: var(--success); margin-bottom: 15px;"></i>
                            <h3>Shipment Data</h3>
                            <p>Export shipment data to Excel for analysis</p>
                            <button class="btn mt-4">Export Excel</button>
                        </div>
                    </div>
                    
                    <div class="card">
                        <div class="card-content text-center">
                            <i class="fas fa-chart-line" style="font-size: 2.5rem; color: var(--accent-blue); margin-bottom: 15px;"></i>
                            <h3>Analytics</h3>
                            <p>View detailed analytics and insights</p>
                            <button class="btn mt-4">View Analytics</button>
                        </div>
                    </div>
                </div>
                
                <div class="table-container">
                    <div class="table-header">
                        <h3>Report History</h3>
                    </div>
                    <div class="table-responsive">
                        <table>
                            <thead>
                                <tr>
                                    <th>Report Name</th>
                                    <th>Generated By</th>
                                    <th>Date</th>
                                    <th>Type</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>Q3 2023 Performance Report</td>
                                    <td>Admin User</td>
                                    <td>Oct 15, 2023</td>
                                    <td>PDF</td>
                                    <td>
                                        <button class="btn-action btn-view">View</button>
                                        <button class="btn-action btn-delete">Delete</button>
                                    </td>
                                </tr>
                                <tr>
                                    <td>September Shipment Data</td>
                                    <td>Admin User</td>
                                    <td>Oct 1, 2023</td>
                                    <td>Excel</td>
                                    <td>
                                        <button class="btn-action btn-view">View</button>
                                        <button class="btn-action btn-delete">Delete</button>
                                    </td>
                                </tr>
                                <tr>
                                    <td>Customer Growth Analysis</td>
                                    <td>Admin User</td>
                                    <td>Sep 20, 2023</td>
                                    <td>PDF</td>
                                    <td>
                                        <button class="btn-action btn-view">View</button>
                                        <button class="btn-action btn-delete">Delete</button>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </section>
            
            <!-- Settings Page -->
            <section id="settingsPage" class="admin-page hidden">
                <div class="dashboard-row">
                    <div class="table-container">
                        <div class="table-header">
                            <h3>System Settings</h3>
                        </div>
                        
                        <div class="tabs">
                            <div class="tab active" data-tab="general">General</div>
                            <div class="tab" data-tab="notifications">Notifications</div>
                            <div class="tab" data-tab="users">Users</div>
                        </div>
                        
                        <div class="tab-content active" id="tabGeneral">
                            <form id="generalSettingsForm">
                                <div class="form-row">
                                    <div class="form-group">
                                        <label for="companyName">Company Name</label>
                                        <input type="text" id="companyName" class="form-control" value="Lilsley Logistics">
                                    </div>
                                    <div class="form-group">
                                        <label for="contactEmail">Contact Email</label>
                                        <input type="email" id="contactEmail" class="form-control" value="admin@lilsleylogistics.com">
                                    </div>
                                </div>
                                
                                <div class="form-row">
                                    <div class="form-group">
                                        <label for="contactPhone">Contact Phone</label>
                                        <input type="text" id="contactPhone" class="form-control" value="+1 (800) 555-LOGISTICS">
                                    </div>
                                    <div class="form-group">
                                        <label for="timezone">Timezone</label>
                                        <select id="timezone" class="form-control">
                                            <option>UTC-05:00 Eastern Time</option>
                                            <option>UTC-08:00 Pacific Time</option>
                                            <option>UTC+00:00 GMT</option>
                                        </select>
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label for="companyAddress">Company Address</label>
                                    <textarea id="companyAddress" class="form-control" rows="3">123 Logistics Drive, Suite 500, Springfield, ST 12345</textarea>
                                </div>
                                
                                <div class="form-actions">
                                    <button type="submit" class="btn">Save Changes</button>
                                    <button type="button" class="btn btn-cancel">Cancel</button>
                                </div>
                            </form>
                        </div>
                        
                        <div class="tab-content" id="tabUsers">
                            <div class="table-responsive">
                                <table>
                                    <thead>
                                        <tr>
                                            <th>Username</th>
                                            <th>Name</th>
                                            <th>Email</th>
                                            <th>Role</th>
                                            <th>Status</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>admin</td>
                                            <td>Admin User</td>
                                            <td>admin@lilsleylogistics.com</td>
                                            <td>Administrator</td>
                                            <td><span class="status delivered">Active</span></td>
                                            <td>
                                                <button class="btn-action btn-edit">Edit</button>
                                                <button class="btn-action btn-delete">Delete</button>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>manager1</td>
                                            <td>Operations Manager</td>
                                            <td>manager@lilsleylogistics.com</td>
                                            <td>Manager</td>
                                            <td><span class="status delivered">Active</span></td>
                                            <td>
                                                <button class="btn-action btn-edit">Edit</button>
                                                <button class="btn-action btn-delete">Delete</button>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>staff1</td>
                                            <td>Support Staff</td>
                                            <td>staff@lilsleylogistics.com</td>
                                            <td>Staff</td>
                                            <td><span class="status pending">Inactive</span></td>
                                            <td>
                                                <button class="btn-action btn-edit">Edit</button>
                                                <button class="btn-action btn-delete">Delete</button>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </main>
    </div>

    <!-- Modal for Adding/Editing Items -->
    <div id="modalOverlay" class="modal-overlay hidden">
        <div class="modal-content" id="modalContent">
            <!-- Modal content will be populated by JavaScript -->
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
        // Sample Data
        const sampleServices = [
            { 
                id: 1, 
                name: "Freight Forwarding", 
                description: "Air, sea, and road freight solutions with global coverage and competitive pricing.", 
                icon: "fas fa-plane",
                category: "Shipping",
                status: "active",
                features: ["Global Coverage", "Competitive Pricing", "Multiple Transport Options"]
            },
            { 
                id: 2, 
                name: "Warehousing & Storage", 
                description: "Secure storage solutions with inventory management and distribution services.", 
                icon: "fas fa-warehouse",
                category: "Storage",
                status: "active",
                features: ["Secure Storage", "Inventory Management", "Distribution Services"]
            },
            { 
                id: 3, 
                name: "Last-Mile Delivery", 
                description: "Efficient final delivery to customers with real-time tracking and notifications.", 
                icon: "fas fa-truck",
                category: "Delivery",
                status: "active",
                features: ["Real-time Tracking", "Customer Notifications", "Efficient Routing"]
            },
            { 
                id: 4, 
                name: "Supply Chain Management", 
                description: "End-to-end supply chain optimization and visibility solutions.", 
                icon: "fas fa-link",
                category: "Management",
                status: "active",
                features: ["End-to-End Visibility", "Optimization", "Analytics"]
            },
            { 
                id: 5, 
                name: "Customs Clearance", 
                description: "Expert handling of customs documentation and clearance processes.", 
                icon: "fas fa-passport",
                category: "International",
                status: "active",
                features: ["Documentation", "Expert Handling", "Fast Processing"]
            },
            { 
                id: 6, 
                name: "Real-Time Tracking", 
                description: "Advanced tracking systems providing real-time visibility of your shipments.", 
                icon: "fas fa-satellite",
                category: "Technology",
                status: "active",
                features: ["Real-time Updates", "GPS Tracking", "Notifications"]
            }
        ];

        const sampleProducts = [
            { 
                id: 1, 
                name: "Heavy-Duty Shipping Boxes", 
                description: "Durable corrugated boxes for secure shipping of various items.", 
                price: 34.99,
                category: "Packaging",
                image: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
                status: "active",
                stock: 245
            },
            { 
                id: 2, 
                name: "Bubble Wrap Roll", 
                description: "Protective bubble wrap for cushioning fragile items during transit.", 
                price: 18.50,
                category: "Packaging",
                image: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
                status: "active",
                stock: 120
            },
            { 
                id: 3, 
                name: "Standard Wooden Pallet", 
                description: "Standard 48\" x 40\" wooden pallet for warehouse storage and shipping.", 
                price: 24.99,
                category: "Equipment",
                image: "https://images.unsplash.com/photo-1600687615241-6e1e16d2d2a3?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
                status: "active",
                stock: 89
            },
            { 
                id: 4, 
                name: "Hand Pallet Truck", 
                description: "Manual pallet jack for moving loaded pallets in warehouses.", 
                price: 899.99,
                category: "Equipment",
                image: "https://images.unsplash.com/photo-1578575437130-527eed3abbec?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
                status: "active",
                stock: 15
            },
            { 
                id: 5, 
                name: "GPS Tracking Device", 
                description: "Real-time GPS tracker with long battery life for shipment monitoring.", 
                price: 149.99,
                category: "Tracking",
                image: "https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
                status: "active",
                stock: 42
            },
            { 
                id: 6, 
                name: "Fleet Management Software", 
                description: "Software suite for managing logistics operations and vehicle fleets.", 
                price: 299.99,
                category: "Software",
                image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
                status: "active",
                stock: 23
            }
        ];

        const sampleShipments = [
            { id: 1, tracking: "LL789456123", customer: "John Smith", origin: "Los Angeles, USA", destination: "New York, USA", shipDate: "2023-10-15", status: "in-transit" },
            { id: 2, tracking: "LL789456124", customer: "Global Retail Co.", origin: "Shanghai, China", destination: "London, UK", shipDate: "2023-10-12", status: "delivered" },
            { id: 3, tracking: "LL789456125", customer: "TechCorp Inc.", origin: "Tokyo, Japan", destination: "Sydney, Australia", shipDate: "2023-10-18", status: "pending" }
        ];

        const sampleInventory = [
            { id: 1, productId: "PROD001", name: "Heavy-Duty Shipping Boxes", category: "Packaging", quantity: 245, location: "Warehouse A", lastUpdated: "2023-10-15" },
            { id: 2, productId: "PROD002", name: "Bubble Wrap Roll", category: "Packaging", quantity: 120, location: "Warehouse B", lastUpdated: "2023-10-14" }
        ];

        const sampleOrders = [
            { id: 1, orderNumber: "ORD00123", customer: "John Smith", date: "2023-10-15", amount: "$345.99", payment: "Credit Card", status: "Completed" },
            { id: 2, orderNumber: "ORD00124", customer: "Global Retail Co.", date: "2023-10-14", amount: "$1,245.50", payment: "Bank Transfer", status: "Processing" }
        ];

        const sampleCustomers = [
            { id: 1, customerId: "CUST001", name: "John Smith", email: "john.smith@email.com", phone: "+1 (555) 123-4567", shipments: 12 },
            { id: 2, customerId: "CUST002", name: "Global Retail Co.", email: "orders@globalretail.com", phone: "+1 (555) 234-5678", shipments: 45 }
        ];

        // DOM Elements
        const loginPage = document.getElementById('loginPage');
        const dashboard = document.getElementById('dashboard');
        const loginForm = document.getElementById('loginForm');
        const logoutBtn = document.getElementById('logoutBtn');
        const adminNavLinks = document.querySelectorAll('.admin-nav-link');
        const adminPages = document.querySelectorAll('.admin-page');
        const pageTitle = document.getElementById('pageTitle');
        const tabs = document.querySelectorAll('.tab');
        const tabContents = document.querySelectorAll('.tab-content');
        const modalOverlay = document.getElementById('modalOverlay');
        const modalContent = document.getElementById('modalContent');
        const servicesGrid = document.getElementById('servicesGrid');
        const productsGrid = document.getElementById('productsGrid');
        
        // Charts
        let shipmentChart, customerChart;

        // Initialize the application
        function init() {
            // Check if user is already logged in
            if (localStorage.getItem('adminLoggedIn') === 'true') {
                showDashboard();
            }
            
            // Set up event listeners
            setupEventListeners();
            
            // Load sample data into tables
            populateServicesGrid();
            populateProductsGrid();
            populateShipmentsTable();
            populateInventoryTable();
            populateOrdersTable();
            populateCustomersTable();
            
            // Initialize charts
            initCharts();
        }
        
        // Set up event listeners
        function setupEventListeners() {
            // Login form submission
            loginForm.addEventListener('submit', (e) => {
                e.preventDefault();
                const username = document.getElementById('username').value;
                const password = document.getElementById('password').value;
                
                // Simple authentication (in real app, this would be server-side)
                if (username === 'admin' && password === 'password123') {
                    localStorage.setItem('adminLoggedIn', 'true');
                    showDashboard();
                } else {
                    alert('Invalid username or password. Use: admin / password123');
                }
            });
            
            // Logout button
            logoutBtn.addEventListener('click', () => {
                localStorage.removeItem('adminLoggedIn');
                showLogin();
            });
            
            // Navigation links
            adminNavLinks.forEach(link => {
                link.addEventListener('click', (e) => {
                    e.preventDefault();
                    const page = link.getAttribute('data-page');
                    showPage(page);
                    
                    // Update active nav link
                    adminNavLinks.forEach(navLink => navLink.classList.remove('active'));
                    link.classList.add('active');
                });
            });
            
            // Tabs
            tabs.forEach(tab => {
                tab.addEventListener('click', () => {
                    const tabId = tab.getAttribute('data-tab');
                    
                    // Update active tab
                    tabs.forEach(t => t.classList.remove('active'));
                    tab.classList.add('active');
                    
                    // Show corresponding content
                    tabContents.forEach(content => {
                        if (content.id === `tab${tabId.charAt(0).toUpperCase() + tabId.slice(1)}`) {
                            content.classList.add('active');
                        } else {
                            content.classList.remove('active');
                        }
                    });
                    
                    // Filter services/products based on tab
                    if (tab.closest('#servicesPage')) {
                        filterServices(tabId);
                    } else if (tab.closest('#productsPage')) {
                        filterProducts(tabId);
                    }
                });
            });
            
            // Add buttons
            document.getElementById('addServiceBtn')?.addEventListener('click', () => showServiceModal());
            document.getElementById('addProductBtn')?.addEventListener('click', () => showProductModal());
            document.getElementById('addShipmentBtn')?.addEventListener('click', () => showShipmentModal());
            document.getElementById('addInventoryBtn')?.addEventListener('click', () => showInventoryModal());
            document.getElementById('addCustomerBtn')?.addEventListener('click', () => showCustomerModal());
            
            // Modal overlay click
            modalOverlay.addEventListener('click', (e) => {
                if (e.target === modalOverlay) {
                    hideModal();
                }
            });
            
            // Settings form submission
            document.getElementById('generalSettingsForm')?.addEventListener('submit', (e) => {
                e.preventDefault();
                alert('Settings saved successfully!');
                hideModal();
            });
        }
        
        // Show login page
        function showLogin() {
            loginPage.classList.remove('hidden');
            dashboard.classList.add('hidden');
        }
        
        // Show dashboard
        function showDashboard() {
            loginPage.classList.add('hidden');
            dashboard.classList.remove('hidden');
            showPage('dashboard');
        }
        
        // Show specific page
        function showPage(pageId) {
            // Update page title
            const pageTitles = {
                'dashboard': 'Dashboard Overview',
                'services': 'Services Management',
                'products': 'Products Management',
                'shipments': 'Shipment Management',
                'inventory': 'Inventory Management',
                'orders': 'Order Management',
                'customers': 'Customer Management',
                'reports': 'Reports & Analytics',
                'settings': 'System Settings'
            };
            
            pageTitle.textContent = pageTitles[pageId] || 'Dashboard';
            
            // Show selected page, hide others
            adminPages.forEach(page => {
                if (page.id === `${pageId}Page`) {
                    page.classList.remove('hidden');
                } else {
                    page.classList.add('hidden');
                }
            });
            
            // Refresh data if needed
            if (pageId === 'services') {
                populateServicesGrid();
            } else if (pageId === 'products') {
                populateProductsGrid();
            }
        }
        
        // Populate services grid
        function populateServicesGrid() {
            if (!servicesGrid) return;
            
            servicesGrid.innerHTML = '';
            
            sampleServices.forEach(service => {
                const serviceItem = document.createElement('div');
                serviceItem.className = 'service-item';
                serviceItem.setAttribute('data-category', service.category);
                serviceItem.setAttribute('data-status', service.status);
                
                serviceItem.innerHTML = `
                    <div class="service-header">
                        <div class="service-icon">
                            <i class="${service.icon}"></i>
                        </div>
                        <div class="service-actions">
                            <button class="btn-action btn-edit" onclick="editService(${service.id})">Edit</button>
                            <button class="btn-action btn-delete" onclick="deleteService(${service.id})">Delete</button>
                        </div>
                    </div>
                    <div class="service-content">
                        <h4>${service.name}</h4>
                        <p>${service.description}</p>
                        <div class="service-category">${service.category}</div>
                        <div class="service-features">
                            <small><strong>Features:</strong> ${service.features.join(', ')}</small>
                        </div>
                    </div>
                `;
                
                servicesGrid.appendChild(serviceItem);
            });
        }
        
        // Populate products grid
        function populateProductsGrid() {
            if (!productsGrid) return;
            
            productsGrid.innerHTML = '';
            
            sampleProducts.forEach(product => {
                const productItem = document.createElement('div');
                productItem.className = 'product-item';
                productItem.setAttribute('data-category', product.category);
                productItem.setAttribute('data-status', product.status);
                
                productItem.innerHTML = `
                    <div class="product-header">
                        <div class="product-icon">
                            <i class="fas fa-box"></i>
                        </div>
                        <div class="product-actions">
                            <button class="btn-action btn-edit" onclick="editProduct(${product.id})">Edit</button>
                            <button class="btn-action btn-delete" onclick="deleteProduct(${product.id})">Delete</button>
                        </div>
                    </div>
                    <div class="product-content">
                        <h4>${product.name}</h4>
                        <p>${product.description}</p>
                        <div class="product-price">$${product.price.toFixed(2)}</div>
                        <div class="product-category">${product.category}</div>
                        <div class="product-stock">
                            <small><strong>Stock:</strong> ${product.stock} units</small>
                        </div>
                    </div>
                `;
                
                productsGrid.appendChild(productItem);
            });
        }
        
        // Filter services by category/status
        function filterServices(filter) {
            const serviceItems = document.querySelectorAll('.service-item');
            
            serviceItems.forEach(item => {
                if (filter === 'all') {
                    item.style.display = 'block';
                } else if (filter === 'active') {
                    if (item.getAttribute('data-status') === 'active') {
                        item.style.display = 'block';
                    } else {
                        item.style.display = 'none';
                    }
                } else if (filter === 'inactive') {
                    if (item.getAttribute('data-status') === 'inactive') {
                        item.style.display = 'block';
                    } else {
                        item.style.display = 'none';
                    }
                } else {
                    if (item.getAttribute('data-category') === filter) {
                        item.style.display = 'block';
                    } else {
                        item.style.display = 'none';
                    }
                }
            });
        }
        
        // Filter products by category
        function filterProducts(filter) {
            const productItems = document.querySelectorAll('.product-item');
            
            productItems.forEach(item => {
                if (filter === 'all') {
                    item.style.display = 'block';
                } else if (item.getAttribute('data-category') === filter) {
                    item.style.display = 'block';
                } else {
                    item.style.display = 'none';
                }
            });
        }
        
        // Populate other tables with sample data
        function populateShipmentsTable() {
            const tableBody = document.getElementById('shipmentsTableBody');
            if (!tableBody) return;
            
            tableBody.innerHTML = '';
            
            sampleShipments.forEach(shipment => {
                const statusClass = shipment.status;
                const statusText = shipment.status.charAt(0).toUpperCase() + shipment.status.slice(1).replace('-', ' ');
                
                const row = document.createElement('tr');
                row.innerHTML = `
                    <td>${shipment.tracking}</td>
                    <td>${shipment.customer}</td>
                    <td>${shipment.origin}</td>
                    <td>${shipment.destination}</td>
                    <td>${shipment.shipDate}</td>
                    <td><span class="status ${statusClass}">${statusText}</span></td>
                    <td>
                        <button class="btn-action btn-view" onclick="viewShipment(${shipment.id})">View</button>
                        <button class="btn-action btn-edit" onclick="editShipment(${shipment.id})">Edit</button>
                        <button class="btn-action btn-delete" onclick="deleteShipment(${shipment.id})">Delete</button>
                    </td>
                `;
                
                tableBody.appendChild(row);
            });
        }
        
        function populateInventoryTable() {
            const tableBody = document.getElementById('inventoryTableBody');
            if (!tableBody) return;
            
            tableBody.innerHTML = '';
            
            sampleInventory.forEach(item => {
                const row = document.createElement('tr');
                row.innerHTML = `
                    <td>${item.productId}</td>
                    <td>${item.name}</td>
                    <td>${item.category}</td>
                    <td>${item.quantity}</td>
                    <td>${item.location}</td>
                    <td>${item.lastUpdated}</td>
                    <td>
                        <button class="btn-action btn-view" onclick="viewInventory(${item.id})">View</button>
                        <button class="btn-action btn-edit" onclick="editInventory(${item.id})">Edit</button>
                        <button class="btn-action btn-delete" onclick="deleteInventory(${item.id})">Delete</button>
                    </td>
                `;
                
                tableBody.appendChild(row);
            });
        }
        
        function populateOrdersTable() {
            const tableBody = document.getElementById('ordersTableBody');
            if (!tableBody) return;
            
            tableBody.innerHTML = '';
            
            sampleOrders.forEach(order => {
                const row = document.createElement('tr');
                row.innerHTML = `
                    <td>${order.orderNumber}</td>
                    <td>${order.customer}</td>
                    <td>${order.date}</td>
                    <td>${order.amount}</td>
                    <td>${order.payment}</td>
                    <td><span class="status ${order.status.toLowerCase()}">${order.status}</span></td>
                    <td>
                        <button class="btn-action btn-view" onclick="viewOrder(${order.id})">View</button>
                        <button class="btn-action btn-edit" onclick="editOrder(${order.id})">Edit</button>
                    </td>
                `;
                
                tableBody.appendChild(row);
            });
        }
        
        function populateCustomersTable() {
            const tableBody = document.getElementById('customersTableBody');
            if (!tableBody) return;
            
            tableBody.innerHTML = '';
            
            sampleCustomers.forEach(customer => {
                const row = document.createElement('tr');
                row.innerHTML = `
                    <td>${customer.customerId}</td>
                    <td>${customer.name}</td>
                    <td>${customer.email}</td>
                    <td>${customer.phone}</td>
                    <td>${customer.shipments}</td>
                    <td>
                        <button class="btn-action btn-view" onclick="viewCustomer(${customer.id})">View</button>
                        <button class="btn-action btn-edit" onclick="editCustomer(${customer.id})">Edit</button>
                        <button class="btn-action btn-delete" onclick="deleteCustomer(${customer.id})">Delete</button>
                    </td>
                `;
                
                tableBody.appendChild(row);
            });
        }
        
        // Initialize charts
        function initCharts() {
            // Shipment Chart
            const shipmentCtx = document.getElementById('shipmentChart');
            if (shipmentCtx) {
                shipmentChart = new Chart(shipmentCtx, {
                    type: 'line',
                    data: {
                        labels: ['Oct 1', 'Oct 5', 'Oct 10', 'Oct 15', 'Oct 20', 'Oct 25', 'Oct 30'],
                        datasets: [{
                            label: 'Shipments',
                            data: [65, 78, 66, 84, 105, 120, 98],
                            borderColor: '#3a86ff',
                            backgroundColor: 'rgba(58, 134, 255, 0.1)',
                            borderWidth: 2,
                            fill: true,
                            tension: 0.4
                        }]
                    },
                    options: {
                        responsive: true,
                        maintainAspectRatio: false,
                        plugins: {
                            legend: {
                                display: false
                            }
                        },
                        scales: {
                            y: {
                                beginAtZero: true,
                                grid: {
                                    color: 'rgba(0, 0, 0, 0.05)'
                                }
                            },
                            x: {
                                grid: {
                                    color: 'rgba(0, 0, 0, 0.05)'
                                }
                            }
                        }
                    }
                });
            }
            
            // Customer Chart
            const customerCtx = document.getElementById('customerChart');
            if (customerCtx) {
                customerChart = new Chart(customerCtx, {
                    type: 'bar',
                    data: {
                        labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct'],
                        datasets: [{
                            label: 'New Customers',
                            data: [12, 19, 15, 25, 22, 30, 28, 35, 32, 40],
                            backgroundColor: 'rgba(40, 167, 69, 0.7)',
                            borderColor: 'rgba(40, 167, 69, 1)',
                            borderWidth: 1
                        }]
                    },
                    options: {
                        responsive: true,
                        maintainAspectRatio: false,
                        plugins: {
                            legend: {
                                display: false
                            }
                        },
                        scales: {
                            y: {
                                beginAtZero: true,
                                grid: {
                                    color: 'rgba(0, 0, 0, 0.05)'
                                }
                            },
                            x: {
                                grid: {
                                    color: 'rgba(0, 0, 0, 0.05)'
                                }
                            }
                        }
                    }
                });
            }
        }
        
        // Modal functions
        function showModal(title, content) {
            modalContent.innerHTML = `
                <h3>${title}</h3>
                ${content}
                <div class="form-actions" style="margin-top: 20px;">
                    <button type="button" class="btn" id="modalSubmit">Submit</button>
                    <button type="button" class="btn btn-cancel" onclick="hideModal()">Cancel</button>
                </div>
            `;
            modalOverlay.classList.remove('hidden');
        }
        
        function hideModal() {
            modalOverlay.classList.add('hidden');
        }
        
        // Show service modal
        function showServiceModal(serviceId = null) {
            const isEdit = serviceId !== null;
            const service = isEdit ? sampleServices.find(s => s.id === serviceId) : null;
            
            const title = isEdit ? 'Edit Service' : 'Add New Service';
            
            const content = `
                <form id="serviceForm" style="margin-top: 20px;">
                    <div class="form-row">
                        <div class="form-group">
                            <label for="modalServiceName">Service Name</label>
                            <input type="text" id="modalServiceName" class="form-control" value="${service ? service.name : ''}" required>
                        </div>
                        <div class="form-group">
                            <label for="modalServiceCategory">Category</label>
                            <select id="modalServiceCategory" class="form-control">
                                <option value="Shipping" ${service && service.category === 'Shipping' ? 'selected' : ''}>Shipping</option>
                                <option value="Storage" ${service && service.category === 'Storage' ? 'selected' : ''}>Storage</option>
                                <option value="Delivery" ${service && service.category === 'Delivery' ? 'selected' : ''}>Delivery</option>
                                <option value="Management" ${service && service.category === 'Management' ? 'selected' : ''}>Management</option>
                                <option value="International" ${service && service.category === 'International' ? 'selected' : ''}>International</option>
                                <option value="Technology" ${service && service.category === 'Technology' ? 'selected' : ''}>Technology</option>
                            </select>
                        </div>
                    </div>
                    
                    <div class="form-row">
                        <div class="form-group">
                            <label for="modalServiceIcon">Icon</label>
                            <select id="modalServiceIcon" class="form-control">
                                <option value="fas fa-plane" ${service && service.icon === 'fas fa-plane' ? 'selected' : ''}>Air Freight</option>
                                <option value="fas fa-ship" ${service && service.icon === 'fas fa-ship' ? 'selected' : ''}>Sea Freight</option>
                                <option value="fas fa-truck" ${service && service.icon === 'fas fa-truck' ? 'selected' : ''}>Road Freight</option>
                                <option value="fas fa-warehouse" ${service && service.icon === 'fas fa-warehouse' ? 'selected' : ''}>Warehousing</option>
                                <option value="fas fa-box" ${service && service.icon === 'fas fa-box' ? 'selected' : ''}>Packaging</option>
                                <option value="fas fa-passport" ${service && service.icon === 'fas fa-passport' ? 'selected' : ''}>Customs</option>
                                <option value="fas fa-satellite" ${service && service.icon === 'fas fa-satellite' ? 'selected' : ''}>Tracking</option>
                                <option value="fas fa-link" ${service && service.icon === 'fas fa-link' ? 'selected' : ''}>Supply Chain</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="modalServiceStatus">Status</label>
                            <select id="modalServiceStatus" class="form-control">
                                <option value="active" ${service && service.status === 'active' ? 'selected' : ''}>Active</option>
                                <option value="inactive" ${service && service.status === 'inactive' ? 'selected' : ''}>Inactive</option>
                            </select>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="modalServiceDescription">Description</label>
                        <textarea id="modalServiceDescription" class="form-control" rows="4" required>${service ? service.description : ''}</textarea>
                    </div>
                    
                    <div class="form-group">
                        <label for="modalServiceFeatures">Features (comma separated)</label>
                        <input type="text" id="modalServiceFeatures" class="form-control" value="${service ? service.features.join(', ') : ''}" placeholder="Feature 1, Feature 2, Feature 3">
                    </div>
                </form>
            `;
            
            showModal(title, content);
            
            // Handle form submission
            document.getElementById('modalSubmit').addEventListener('click', () => {
                // In a real app, this would send data to server
                alert(isEdit ? 'Service updated successfully!' : 'New service added successfully!');
                hideModal();
                
                // Refresh the grid
                populateServicesGrid();
            });
        }
        
        // Show product modal
        function showProductModal(productId = null) {
            const isEdit = productId !== null;
            const product = isEdit ? sampleProducts.find(p => p.id === productId) : null;
            
            const title = isEdit ? 'Edit Product' : 'Add New Product';
            
            const content = `
                <form id="productForm" style="margin-top: 20px;">
                    <div class="form-row">
                        <div class="form-group">
                            <label for="modalProductName">Product Name</label>
                            <input type="text" id="modalProductName" class="form-control" value="${product ? product.name : ''}" required>
                        </div>
                        <div class="form-group">
                            <label for="modalProductCategory">Category</label>
                            <select id="modalProductCategory" class="form-control">
                                <option value="Packaging" ${product && product.category === 'Packaging' ? 'selected' : ''}>Packaging</option>
                                <option value="Equipment" ${product && product.category === 'Equipment' ? 'selected' : ''}>Equipment</option>
                                <option value="Tracking" ${product && product.category === 'Tracking' ? 'selected' : ''}>Tracking</option>
                                <option value="Software" ${product && product.category === 'Software' ? 'selected' : ''}>Software</option>
                            </select>
                        </div>
                    </div>
                    
                    <div class="form-row">
                        <div class="form-group">
                            <label for="modalProductPrice">Price ($)</label>
                            <input type="number" id="modalProductPrice" class="form-control" step="0.01" value="${product ? product.price : ''}" required>
                        </div>
                        <div class="form-group">
                            <label for="modalProductStock">Stock</label>
                            <input type="number" id="modalProductStock" class="form-control" value="${product ? product.stock : ''}" required>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="modalProductDescription">Description</label>
                        <textarea id="modalProductDescription" class="form-control" rows="4" required>${product ? product.description : ''}</textarea>
                    </div>
                    
                    <div class="form-group">
                        <label>Product Image</label>
                        <div class="image-upload-container" onclick="document.getElementById('productImageUpload').click()">
                            <i class="fas fa-cloud-upload-alt"></i>
                            <p>Click to upload product image</p>
                            <small>Recommended: 500x500px, JPG or PNG</small>
                            ${product && product.image ? `<div class="image-preview"><img src="${product.image}" alt="Preview"></div>` : ''}
                        </div>
                        <input type="file" id="productImageUpload" accept="image/*" style="display: none;">
                    </div>
                </form>
            `;
            
            showModal(title, content);
            
            // Handle form submission
            document.getElementById('modalSubmit').addEventListener('click', () => {
                alert(isEdit ? 'Product updated successfully!' : 'New product added successfully!');
                hideModal();
                
                // Refresh the grid
                populateProductsGrid();
            });
        }
        
        // Show shipment modal
        function showShipmentModal(shipmentId = null) {
            const isEdit = shipmentId !== null;
            const shipment = isEdit ? sampleShipments.find(s => s.id === shipmentId) : null;
            
            const title = isEdit ? 'Edit Shipment' : 'Add New Shipment';
            
            const content = `
                <form id="shipmentForm" style="margin-top: 20px;">
                    <div class="form-row">
                        <div class="form-group">
                            <label for="modalTracking">Tracking Number</label>
                            <input type="text" id="modalTracking" class="form-control" value="${shipment ? shipment.tracking : ''}" required>
                        </div>
                        <div class="form-group">
                            <label for="modalCustomer">Customer</label>
                            <input type="text" id="modalCustomer" class="form-control" value="${shipment ? shipment.customer : ''}" required>
                        </div>
                    </div>
                    
                    <div class="form-row">
                        <div class="form-group">
                            <label for="modalOrigin">Origin</label>
                            <input type="text" id="modalOrigin" class="form-control" value="${shipment ? shipment.origin : ''}" required>
                        </div>
                        <div class="form-group">
                            <label for="modalDestination">Destination</label>
                            <input type="text" id="modalDestination" class="form-control" value="${shipment ? shipment.destination : ''}" required>
                        </div>
                    </div>
                    
                    <div class="form-row">
                        <div class="form-group">
                            <label for="modalShipDate">Ship Date</label>
                            <input type="date" id="modalShipDate" class="form-control" value="${shipment ? shipment.shipDate : ''}" required>
                        </div>
                        <div class="form-group">
                            <label for="modalStatus">Status</label>
                            <select id="modalStatus" class="form-control">
                                <option value="pending" ${shipment && shipment.status === 'pending' ? 'selected' : ''}>Pending</option>
                                <option value="in-transit" ${shipment && shipment.status === 'in-transit' ? 'selected' : ''}>In Transit</option>
                                <option value="delivered" ${shipment && shipment.status === 'delivered' ? 'selected' : ''}>Delivered</option>
                                <option value="cancelled" ${shipment && shipment.status === 'cancelled' ? 'selected' : ''}>Cancelled</option>
                            </select>
                        </div>
                    </div>
                </form>
            `;
            
            showModal(title, content);
            
            // Handle form submission
            document.getElementById('modalSubmit').addEventListener('click', () => {
                alert(isEdit ? 'Shipment updated successfully!' : 'New shipment added successfully!');
                hideModal();
                
                // Refresh the table
                populateShipmentsTable();
            });
        }
        
        // Show inventory modal
        function showInventoryModal(inventoryId = null) {
            const isEdit = inventoryId !== null;
            const item = isEdit ? sampleInventory.find(i => i.id === inventoryId) : null;
            
            const title = isEdit ? 'Edit Inventory Item' : 'Add New Inventory Item';
            
            const content = `
                <form id="inventoryForm" style="margin-top: 20px;">
                    <div class="form-row">
                        <div class="form-group">
                            <label for="modalProductId">Product ID</label>
                            <input type="text" id="modalProductId" class="form-control" value="${item ? item.productId : ''}" required>
                        </div>
                        <div class="form-group">
                            <label for="modalProductName">Product Name</label>
                            <input type="text" id="modalProductName" class="form-control" value="${item ? item.name : ''}" required>
                        </div>
                    </div>
                    
                    <div class="form-row">
                        <div class="form-group">
                            <label for="modalCategory">Category</label>
                            <select id="modalCategory" class="form-control">
                                <option value="Packaging" ${item && item.category === 'Packaging' ? 'selected' : ''}>Packaging</option>
                                <option value="Equipment" ${item && item.category === 'Equipment' ? 'selected' : ''}>Equipment</option>
                                <option value="Tracking" ${item && item.category === 'Tracking' ? 'selected' : ''}>Tracking</option>
                                <option value="Software" ${item && item.category === 'Software' ? 'selected' : ''}>Software</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="modalQuantity">Quantity</label>
                            <input type="number" id="modalQuantity" class="form-control" value="${item ? item.quantity : ''}" required>
                        </div>
                    </div>
                    
                    <div class="form-row">
                        <div class="form-group">
                            <label for="modalLocation">Location</label>
                            <input type="text" id="modalLocation" class="form-control" value="${item ? item.location : ''}" required>
                        </div>
                    </div>
                </form>
            `;
            
            showModal(title, content);
            
            // Handle form submission
            document.getElementById('modalSubmit').addEventListener('click', () => {
                alert(isEdit ? 'Inventory item updated successfully!' : 'New inventory item added successfully!');
                hideModal();
                
                // Refresh the table
                populateInventoryTable();
            });
        }
        
        // Show customer modal
        function showCustomerModal(customerId = null) {
            const isEdit = customerId !== null;
            const customer = isEdit ? sampleCustomers.find(c => c.id === customerId) : null;
            
            const title = isEdit ? 'Edit Customer' : 'Add New Customer';
            
            const content = `
                <form id="customerForm" style="margin-top: 20px;">
                    <div class="form-row">
                        <div class="form-group">
                            <label for="modalCustomerId">Customer ID</label>
                            <input type="text" id="modalCustomerId" class="form-control" value="${customer ? customer.customerId : ''}" required>
                        </div>
                        <div class="form-group">
                            <label for="modalCustomerName">Customer Name</label>
                            <input type="text" id="modalCustomerName" class="form-control" value="${customer ? customer.name : ''}" required>
                        </div>
                    </div>
                    
                    <div class="form-row">
                        <div class="form-group">
                            <label for="modalCustomerEmail">Email</label>
                            <input type="email" id="modalCustomerEmail" class="form-control" value="${customer ? customer.email : ''}" required>
                        </div>
                        <div class="form-group">
                            <label for="modalCustomerPhone">Phone</label>
                            <input type="text" id="modalCustomerPhone" class="form-control" value="${customer ? customer.phone : ''}" required>
                        </div>
                    </div>
                </form>
            `;
            
            showModal(title, content);
            
            // Handle form submission
            document.getElementById('modalSubmit').addEventListener('click', () => {
                alert(isEdit ? 'Customer updated successfully!' : 'New customer added successfully!');
                hideModal();
                
                // Refresh the table
                populateCustomersTable();
            });
        }
        
        // Action functions for services
        function editService(id) {
            showServiceModal(id);
        }
        
        function deleteService(id) {
            if (confirm('Are you sure you want to delete this service?')) {
                alert('Service deleted successfully!');
                // In real app, remove from array and refresh grid
                populateServicesGrid();
            }
        }
        
        // Action functions for products
        function editProduct(id) {
            showProductModal(id);
        }
        
        function deleteProduct(id) {
            if (confirm('Are you sure you want to delete this product?')) {
                alert('Product deleted successfully!');
                // In real app, remove from array and refresh grid
                populateProductsGrid();
            }
        }
        
        // Action functions for shipments
        function viewShipment(id) {
            const shipment = sampleShipments.find(s => s.id === id);
            if (shipment) {
                alert(`Viewing shipment: ${shipment.tracking}\nCustomer: ${shipment.customer}\nStatus: ${shipment.status}`);
            }
        }
        
        function editShipment(id) {
            showShipmentModal(id);
        }
        
        function deleteShipment(id) {
            if (confirm('Are you sure you want to delete this shipment?')) {
                alert('Shipment deleted successfully!');
            }
        }
        
        // Action functions for inventory
        function viewInventory(id) {
            const item = sampleInventory.find(i => i.id === id);
            if (item) {
                alert(`Viewing inventory: ${item.name}\nQuantity: ${item.quantity}\nLocation: ${item.location}`);
            }
        }
        
        function editInventory(id) {
            showInventoryModal(id);
        }
        
        function deleteInventory(id) {
            if (confirm('Are you sure you want to delete this inventory item?')) {
                alert('Inventory item deleted successfully!');
            }
        }
        
        // Action functions for orders
        function viewOrder(id) {
            const order = sampleOrders.find(o => o.id === id);
            if (order) {
                alert(`Viewing order: ${order.orderNumber}\nCustomer: ${order.customer}\nAmount: ${order.amount}`);
            }
        }
        
        function editOrder(id) {
            alert('Edit order functionality would be implemented here');
        }
        
        // Action functions for customers
        function viewCustomer(id) {
            const customer = sampleCustomers.find(c => c.id === id);
            if (customer) {
                alert(`Viewing customer: ${customer.name}\nEmail: ${customer.email}\nShipments: ${customer.shipments}`);
            }
        }
        
        function editCustomer(id) {
            showCustomerModal(id);
        }
        
        function deleteCustomer(id) {
            if (confirm('Are you sure you want to delete this customer?')) {
                alert('Customer deleted successfully!');
            }
        }
        
        // Initialize the application when DOM is loaded
        document.addEventListener('DOMContentLoaded', init);
    </script>
</body>
</html>