<section id="reportsPage" class="admin-page hidden">
                <div class="dashboard-cards mb-4">
                    <div class="card">
                        <div class="card-content text-center">
                            <i class="fas fa-file-pdf" style="font-size: 2.5rem; color: var(--danger); margin-bottom: 15px;"></i>
                            <h3>Monthly Report</h3>
                            <p>Generate and download monthly performance report</p>
                            <button class="btn mt-4">Generate PDF</button>
                        </div>
                    </div>
                    
                    <div class="card">
                        <div class="card-content text-center">
                            <i class="fas fa-file-excel" style="font-size: 2.5rem; color: var(--success); margin-bottom: 15px;"></i>
                            <h3>Shipment Data</h3>
                            <p>Export shipment data to Excel for analysis</p>
                            <button class="btn mt-4">Export Excel</button>
                        </div>
                    </div>
                    
                    <div class="card">
                        <div class="card-content text-center">
                            <i class="fas fa-chart-line" style="font-size: 2.5rem; color: var(--accent-blue); margin-bottom: 15px;"></i>
                            <h3>Analytics</h3>
                            <p>View detailed analytics and insights</p>
                            <button class="btn mt-4">View Analytics</button>
                        </div>
                    </div>
                </div>
                
                <div class="table-container">
                    <div class="table-header">
                        <h3>Report History</h3>
                    </div>
                    <div class="table-responsive">
                        <table>
                            <thead>
                                <tr>
                                    <th>Report Name</th>
                                    <th>Generated By</th>
                                    <th>Date</th>
                                    <th>Type</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>Q3 2023 Performance Report</td>
                                    <td>Admin User</td>
                                    <td>Oct 15, 2023</td>
                                    <td>PDF</td>
                                    <td>
                                        <button class="btn-action btn-view">View</button>
                                        <button class="btn-action btn-delete">Delete</button>
                                    </td>
                                </tr>
                                <tr>
                                    <td>September Shipment Data</td>
                                    <td>Admin User</td>
                                    <td>Oct 1, 2023</td>
                                    <td>Excel</td>
                                    <td>
                                        <button class="btn-action btn-view">View</button>
                                        <button class="btn-action btn-delete">Delete</button>
                                    </td>
                                </tr>
                                <tr>
                                    <td>Customer Growth Analysis</td>
                                    <td>Admin User</td>
                                    <td>Sep 20, 2023</td>
                                    <td>PDF</td>
                                    <td>
                                        <button class="btn-action btn-view">View</button>
                                        <button class="btn-action btn-delete">Delete</button>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </section>