<section id="products" class="page hidden">
            <div class="container">
                <h1 class="page-title">Logistics Products & Equipment</h1>
                <p class="page-subtitle">High-quality logistics products to support your shipping and warehousing operations.</p>

                <div class="product-page">
                    <div class="product-filters">
                        <h3>Filter Products</h3>

                        <div class="filter-group">
                            <h4>Category</h4>
                            <div class="filter-options">
                                <label><input type="checkbox" class="category-filter" value="packaging" checked> Packaging Materials</label>
                                <label><input type="checkbox" class="category-filter" value="equipment" checked> Handling Equipment</label>
                                <label><input type="checkbox" class="category-filter" value="tracking" checked> Tracking Devices</label>
                                <label><input type="checkbox" class="category-filter" value="software" checked> Software & Accessories</label>
                            </div>
                        </div>

                        <div class="filter-group">
                            <h4>Price Range</h4>
                            <div class="filter-options">
                                <label><input type="radio" name="price" class="price-filter" value="all" checked> All Prices</label>
                                <label><input type="radio" name="price" class="price-filter" value="under50"> Under $50</label>
                                <label><input type="radio" name="price" class="price-filter" value="50-200"> $50 - $200</label>
                                <label><input type="radio" name="price" class="price-filter" value="over200"> Over $200</label>
                            </div>
                        </div>

                        <button class="btn" id="applyFilters">Apply Filters</button>
                        <button class="btn btn-outline" id="resetFilters">Reset Filters</button>
                    </div>

                    <div class="products-grid" id="productsGrid">
                        <!-- Product cards will be generated by JavaScript -->
                    </div>
                </div>
            </div>
        </section>
